services:
  # Database
  - type: pserv
    name: booking-system-db
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./backend/Dockerfile.production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booking-db
          property: connectionString
      - key: APP_NAME
        value: RoomBooker
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: pserv
          name: booking-system-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: FRONTEND_URL
        fromService:
          type: web
          name: booking-system-frontend
          envVarKey: RENDER_EXTERNAL_URL
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: SESSION_DRIVER
        value: cookie
      - key: QUEUE_CONNECTION
        value: sync
      - key: SANCTUM_STATEFUL_DOMAINS
        value: localhost:3000,127.0.0.1:3000

  # PostgreSQL Database
  - type: pserv
    name: booking-db
    env: docker
    plan: free
    region: frankfurt

  # Frontend
  - type: web
    name: booking-system-frontend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: pserv
          name: booking-system-backend
          envVarKey: RENDER_EXTERNAL_URL
